#!/usr/bin/env sh
#
# Install dotfiles using stow

set -o errexit -o nounset -o xtrace

archive="${1:?missing archive location}"
action="${2:?missing action}"
target="${3:-${HOME}}"
stow_dir="${XDG_DATA_HOME:-${HOME}/.local/share}/dotfiles/stow"
temp_dir=$(mktemp -d)
trap 'rm -rf "${temp_dir}"' EXIT
dir="$(dirname "${stow_dir}")"
package="$(basename "${stow_dir}")"

mkdir -p "${stow_dir}"
tar -C "${temp_dir}" --strip-components=1 -xzf "${archive}"

case "${action}" in
--delete) ;;
--stow)
    rsync -a --delete "${temp_dir}/" "${stow_dir}/"
    ;;
--simulate)
    dir=$(dirname "${temp_dir}")
    package=$(basename "${temp_dir}")
    ;;
*)
    echo "invalid action '${action}'"
    exit 1
    ;;
esac

stow --verbose --no-folding --target "${target}" --dir "${dir}" "${action}" "${package}"
