name: Build a docker image
description: Build a docker image using kaniko
inputs:
  context:
    default: dir://.
    description: context path
  dockerfile:
    default: Dockerfile
    description: dockerfile path
  destination:
    description: destination
  token:
    description: token for dockerhub
  user:
    description: dockerhub user
    default: shishifubingbot
  auth_target:
    description: auth endpoint
    default: https://index.docker.io/v1/
  dry_run:
    description: if set, do not push
    default: ""
runs:
  using: docker
  image: Dockerfile
