git: git/install ## Run git/install
git/install: git/install-stow ## Install stow package
git/build: git/build-stow ## Build stow package
git/clean: git/clean-stow ## Clean stow package
git/test: git/test-stow ## Test stow package
