#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

submissions_file="${1:?missing submissions file}"
submissions_dir="${2:?missing submissions_dir}"
bazel="$(git rev-parse --show-toplevel)/bazel"
date=$(date '+%y-%m-%d')
branch="dev/add-${date}-leetcode-submissions"
commit="feat(leetcode): add ${date} submissions"

git checkout -B "${branch}"
"${bazel}" run leetcode:download_submissions
"${bazel}" run leetcode:generate_submissions
"${bazel}" run leetcode:format_submissions
git add "${submissions_file}" "${submissions_dir}"
git commit -m "${commit}"
git push origin "${branch}"
gh pr create --fill
gh pr merge --admin --squash --delete-branch
git checkout main
git pull
