require("shishifubing.mapleader")
require("shishifubing.lazy")
require("shishifubing.options")
require("shishifubing.autocmd")
require("shishifubing.filetypes")
require("shishifubing.keymaps").set_no_deps()
