dotfiles/vscode: dotfiles/vscode/install ## Run dotfiles/vscode/install
dotfiles/vscode/install: dotfiles/vscode/install-stow ## Install stow package
dotfiles/vscode/build: dotfiles/vscode/build-stow ## Build stow package
dotfiles/vscode/clean: dotfiles/vscode/clean-stow ## Clean stow package
dotfiles/vscode/test: dotfiles/vscode/test-stow ## Test stow package
