#!/usr/bin/env bash
set -Eeuxo pipefail

packages=(
    make git curl wget unzip stow gpg python3 python3-pip python3-venv
    gpg-agent xxd
)

job="${1:-"${GITHUB_JOB}"}"
action_script="/action/scripts/${job}"

apt-get update
apt-get install -y "${packages[@]}"
git config --global --add safe.directory "${GITHUB_WORKSPACE:-.}"

if [[ -f "${action_script}" ]]; then
    "${action_script}"
else
    make "${job}"
fi
