#!/usr/bin/env python3

import json
import sys
from pathlib import Path
from typing import Any

extensions = {"python3": "py", "golang": "go", "cpp": "cpp", "java": "java"}
comments = {"python3": "#", "golang": "//", "cpp": "//", "java": "//"}
headers = {
    "python3": "",
    "golang": "package submissions",
    "cpp": "",
    "java": "com.shishifubing.dotfiles.submissions",
}


def main() -> None:
    base = sys.argv[1]
    submissions_file = sys.argv[2]
    submissions: dict[str, dict[str, Any]] = {}
    with open(submissions_file, "r") as file:
        submissions = json.loads(file.read())
    for _, submission in submissions.items():
        id = submission["id"]
        status = submission["status_display"]
        if status != "Accepted":
            print(f"Ignoring {id}: {status}")
            continue
        extension = extensions[submission["lang"]]
        comment = comments[submission["lang"]]
        header = headers[submission["lang"]]
        file_name = "-".join(
            (
                str(submission["question_id"]).rjust(5, "0"),
                submission["title_slug"],
                str(submission["id"]),
            )
        )
        path = Path("leetcode") / "submissions" / f"{file_name}.{extension}"
        content = f"""\
{comment} Submission for {submission["title"]}
{comment} Submission url: {base}{submission["url"]}

{header}

{submission["code"]}\
"""
        with open(path, "w") as file:
            file.write(content)
    print(f"wrote {len(submissions)} files")


if __name__ == "__main__":
    main()
