vscode: vscode/install ## Run vscode/install
vscode/install: vscode/install-stow ## Install stow package
vscode/build: vscode/build-stow ## Build stow package
vscode/clean: vscode/clean-stow ## Clean stow package
vscode/test: vscode/test-stow ## Test stow package
