name: Bump version
description: Bump version and update changelog using cz
inputs:
  private_key:
    description: private gpg key to sign commits
    required: true
  passphrase:
    description: passphrase for the private key
  dry_run:
    description: if set, do not push commits
    default: ""
runs:
  using: docker
  image: Dockerfile
