gpg: gpg/install ## Run gpg/instal
gpg/install: gpg/install-stow ## Install stow package
gpg/build: gpg/build-stow ## Build stow package
gpg/test: gpg/test-stow ## Test stow package
gpg/clean: gpg/clean-stow ## Clean stow package
