name: reuse-build

on:
  workflow_call:
    inputs:
      version:
        description: artifact version
        default: 0.0.${{ github.sha }}.${{ github.run_attempt }}
        type: string

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  build:
    name: Build .kar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up JDK 11
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Build
        run: |
          ./mvnw clean verify                  \
            -P buildKar                        \
            -Drevision="${{ inputs.version }}" \
            --show-version                     \
            --batch-mode                       \
            --errors

      - name: Upload artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          path: target/*.kar
          name: plugin
