#!/usr/bin/env sh
set -o errexit -o nounset

package="github.com/bazelbuild/bazelisk"
version="c7c6c19799ff408c48bdce6b7557217ad0050b17" # v1.19.0
bin="${GOPATH:-${HOME}/go}/bin/bazelisk"
if [ ! -x "${bin}" ]; then
    go install "${package}@${version}"
fi
cd "$(git rev-parse --show-toplevel)"
. ./tools/env.sh
exec "${bin}" "${@}"
