#!/usr/bin/env sh
set -o errexit -o nounset -o xtrace

project_dir=$(git -C "${BUILD_WORKING_DIRECTORY}" rev-parse --show-toplevel)
leetcode_bin="${PWD}/${1:?missing bin path}"
shift
submissions_file="${project_dir}/assets/leetcode/submissions.json"
submissions_dir="${project_dir}/assets/leetcode/submissions"
date=$(date '+%y-%m-%d')
branch="dev/add-${date}-leetcode-submissions"
commit="chore(leetcode): add ${date} submissions"

update_submission_file() {
    "${leetcode_bin}" \
        --submissions-file "${submissions_file}" \
        --submissions-dir "${submissions_dir}" \
        update "${@}"
}

generate_submission_dir() {
    "${leetcode_bin}" \
        --submissions-file "${submissions_file}" \
        --submissions-dir "${submissions_dir}" \
        generate
    poetry run black --quiet "${submissions_dir}"
    gofmt -w "${submissions_dir}" || true
    poetry run pre-commit run --files "${submissions_file}" "${submissions_dir}"/* || true
}

update() {
    git checkout -B "${branch}"
    update_submission_file "${@}"
    generate_submission_dir
    git add "${submissions_file}" "${submissions_dir}"
    git commit -m "${commit}"
    git push origin "${branch}"
    gh pr create --fill
    gh pr merge --auto --squash --delete-branch
    git checkout main
    git pull
}

cd "${project_dir}"
"${@}"
