#!/usr/bin/env sh
#
# tools

get_functions() {
    _functions=$(grep -E '^[[:space:]]*[[:alnum:]_]+\(\)[[:space:]]*{[[:space:]]*$' "${0}")
    printf "functions:\n%s" "${_functions}" >&2
}

if [ "${#}" -gt 0 ]; then
    set -o errexit -o nounset -o xtrace
    exec "${@}"
fi
