#!/usr/bin/env sh
#
# tools

#######################################
# Fix for generated golang files not available to IDEs
#   https://github.com/bazelbuild/rules_go/wiki/Editor-setup
#######################################
run_gopackagesdriver() {
    exec "$(dirname "${0}")/../bazel" run -- @rules_go//go/tools/gopackagesdriver "${@}"
}

get_functions() {
    _functions=$(grep -E '^[[:space:]]*[[:alnum:]_]+\(\)[[:space:]]*{[[:space:]]*$' "${0}")
    printf "functions:\n%s" "${_functions}" >&2
}

if [ "${#}" -gt 0 ]; then
    set -o errexit -o nounset -o xtrace
    "${@}"
fi
