name: require-pr-title-lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54  # v5.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: true
