name: require-pr-title-lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9  # v5.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          requireScope: true
