name: reuse-release

on:
  workflow_call:
    inputs:
      draft:
        description: whether the release should be a draft
        type: boolean
        default: false
      download:
        description: whether to download artifacts
        type: boolean
        default: false
      files:
        description: regex describing which artifacts are to be included in the release
        type: string
        default: _artifacts/**/*
      download_path:
        description: path for artifacts
        type: string
        default: _artifacts

env:
  JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  release:
    name: Publish a release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        
      - name: Download artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        if: inputs.download
        with:
          path: ${{ inputs.download_path }}

      - name: Get release info
        id: info
        uses: shishifubing/ci-actions-common/actions/release-info@main
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        if: steps.info.outputs.create == 'true' && steps.info.outputs.body
        with:
          # events triggered by GitHub Actions don't trigger GitHub Actions, so
          # you need to pass custom token to trigger changelog workflow
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          tag_name: ${{ steps.info.outputs.version }}
          name: ${{ steps.info.outputs.version }}
          body: |
            <!-- Automatically generated in ${{ env.JOB_URL }} -->
            
            ${{ steps.info.outputs.body }}
          files: ${{ inputs.files }}
          draft: ${{ inputs.draft }}
