name: reuse-changelog

on:
  workflow_call:

env:
  JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  update:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@ab89eeba5adfbb4ebdaabf7f1a17d76eec6c59c9 # v1.9.1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
          committer: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
          add-paths: CHANGELOG.md
          title: "chore(changelog): add ${{ github.event.release.tag_name }}"
          body: This PR was automatically generated in ${{ env.JOB_URL }}
          labels: chore, repo, size/m
          signoff: true
          branch: chore/changelog/add-version-${{ github.event.release.tag_name }}
          commit-message: |
            chore(changelog): add ${{ github.event.release.tag_name }}

            Job-url: ${{ env.JOB_URL }}

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          gh pr merge                                \
            --delete-branch                          \
            --merge                                  \
            --auto                                   \
            ${{ steps.pr.outputs.pull-request-url }}
