name: Test CI action

on:
  pull_request:

jobs:
  test-ci-action:
    runs-on: ubuntu-latest
    container:
      image: ubuntu@sha256:1395dff3ecc43bbc9c1fb2af3b9d8c0df89ef9ef5f11f7ac69c6e0875862ef08 # 24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./actions/ci
