on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # once a week
concurrency:
  group: ${{ github.workflow_ref }}
jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message , 'bump')"
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - uses: ./bump_version
        with:
          private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
