name: On pull request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}/${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test_makefile:
    runs-on: ubuntu-latest
    container:
      image: ubuntu@sha256:1395dff3ecc43bbc9c1fb2af3b9d8c0df89ef9ef5f11f7ac69c6e0875862ef08 # 24.04
    steps:
      - uses: shishifubing/ci/actions/ci@0bc28347d5f66bb33977a9f2d3ef13cf5c64b243 # v1.21.0
