name: On pull request
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}/${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  test_makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: sudo apt-get update && apt-get install -y stow
      - run: make --debug=b install
      - run: make --debug=b test
  build_image_commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./kaniko
        with:
          dry_run: 1
          dockerfile: images/commitizen.Dockerfile
  test_kaniko:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./kaniko
        with:
          context: dir://kaniko
          dockerfile: kaniko/Dockerfile.test
          destination: shishifubing/test_kaniko:latest
          token: ${{ secrets.CI_DOCKERHUB_TOKEN }}
  test_kaniko_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./kaniko
        with:
          dry_run: 1
          context: dir://kaniko
          dockerfile: kaniko/Dockerfile.test
  test_bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: ./bump_version
        with:
          dry_run: 1
          private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
  test_bump_version_with_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - run: ./bump_version/test_bump_version_commit.sh
      - uses: ./bump_version
        with:
          dry_run: 1
          private_key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
