on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.workflow_ref }}
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: ./kaniko
        with:
          dockerfile: ./images/commitizen.Dockerfile
          destination: shishifubing/commitizen:${{ github.ref_name }}
          token: ${{ secrets.CI_DOCKERHUB_TOKEN }}
