name: release-info
description: get release info

outputs:
  name:
    description: release name
    value: ${{ steps.notes.outputs.name }}
  body:
    description: body of release notes
    value: ${{ steps.notes.outputs.body }}
  version:
    description: release version
    value: ${{ steps.check.outputs.version }}

runs:
  using: composite
  steps:
    - name: Check latest release
      shell: sh
      id: check
      run: |
        latest_gh_release=$(
          gh release view --json tagName --jq .tagName --repo "${{ github.repository }}"
        )
        latest_tag=$(
          gh api                                     \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/tags"   \
            --jq .[0].name
        )

        if [ "${latest_gh_release}" = "${latest_tag}" ]; then
          echo "Release ${latest_gh_release} already exists"
          exit 1
        fi

        echo "version=${latest_tag}" >>"${GITHUB_OUTPUT}"

    - name: Generate release notes
      id: notes
      if: steps.check.outputs.create_release == 'true'
      shell: sh
      run: |
        tag=''
        gh api                                                      \
          --method POST                                             \
          -H "Accept: application/vnd.github+json"                  \
          "/repos/${{ github.repository }}/releases/generate-notes" \
          -f tag_name="${{ steps.check.outputs.version }}"          \
          >release_notes.json

        {
          echo "name=$(jq -r .name release_notes.json)"
          echo "body<<EOF"
          jq -r .body release_notes.json
          echo "EOF"
        } >>"${GITHUB_OUTPUT}"
