name: release-info
description: get release info

outputs:
  name:
    description: release name
    value: ${{ steps.notes.outputs.name }}
  body:
    description: body of release notes
    value: ${{ steps.notes.outputs.body }}
  version:
    description: release version
    value: ${{ steps.info.outputs.current }}
  create:
    description: whether there is a need to create a new release
    value: ${{ steps.info.outputs.create_release }}

runs:
  using: composite
  steps:
    - name: Check latest release
      shell: sh
      id: info
      run: |
        create_release="true"
        latest_gh_release=$(
          gh release view --json tagName --jq .tagName --repo "${{ github.repository }}"
        )
        latest_tag=$(
          gh api                                     \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/tags"   \
            --jq .[0].name
        )

        if [ "${latest_gh_release}" = "${latest_tag}" ]; then
          echo "Release ${latest_gh_release} already exists"
          create_release="false"
        fi
        {
          echo "previous=${latest_gh_release}"
          echo "create_release=${create_release}"
          echo "current=${latest_tag}"
        } >> "${GITHUB_OUTPUT}"

    - name: Generate release notes
      id: notes
      if: steps.check.outputs.create_release == 'true'
      shell: sh
      run: |
        gh api                                                      \
          --method POST                                             \
          -H "Accept: application/vnd.github+json"                  \
          "/repos/${{ github.repository }}/releases/generate-notes" \
          -f tag_name="${{ steps.info.outputs.current }}"           \
          -f previous_tag_name="${{ steps.info.outputs.previous }}" \
          >release_notes.json

        {
          echo "name=$(jq -r .name release_notes.json)"
          echo "body<<EOF"
          jq -r .body release_notes.json
          echo "EOF"
        } >>"${GITHUB_OUTPUT}"
